# Generated by Django 3.1.4 on 2021-07-06 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('fullname', models.CharField(max_length=100)),
                ('phonenumber', models.IntegerField(blank=True)),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('un', 'unkhown')], default='un', max_length=10)),
                ('signing_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('subject', models.CharField(choices=[('T', 'Tech'), ('S', 'Sport'), ('M', 'Music'), ('H', 'History'), ('O', 'Other')], default='O', max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('content', models.TextField(max_length=1000)),
                ('date', models.DateTimeField()),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.user')),
            ],
        ),
    ]
